### ISSUE TITLE
working example?

### ISSUE THREAD

**Issue by ryandeussing** [Teddy-Zhu/vue-smoothscroll#1]
I'd love to see a working demo - the docs are minimal and I'm not getting things working. Thanks!

**Comment by Teddy-Zhu** [comment]
you can refer to  https://github.com/Teddy-Zhu/lc4e-jfinal/blob/master/lc4e-web/src/main/webapp/WEB-INF/views/themes/default/src/app.js

run the code after router render first time
```javascript
    window.SmoothScroll.run();
   //or may failed when vue 2.x , you can try it
    this.$SmoothScroll.run();
```
sorry for the problem.
the project build when vue 1.x
i will rebuild the code in my free time.

**Comment by Teddy-Zhu** [comment]
i improve code and you can see readme.md or demo/index.html now

**Comment by ryandeussing** [comment]
Thanks!
