### ISSUE TITLE
DOCS needs update

### ISSUE THREAD

**Issue by Cholowao** [Teddy-Zhu/vue-smoothscroll#11]
The installation in this link https://www.npmjs.com/package/vue-smooth-scroll should be

```

# install dependency
npm install --save vue-smooth-scroll
// import on your project (less then 1KB gziped) 
import vueSmoothScroll from 'vue-smoothscroll'
Vue.use(vueSmoothScroll)
```

Note the `from  'vue-smoothscroll'`

**Comment by Teddy-Zhu** [comment]
No,  vue-smooth-scroll is a fork version , vue-smoothscroll and vue-smooth-scroll are not the same

**Comment by Cholowao** [comment]
Aha! Got it 💯
