### ISSUE TITLE
missing smoothscroll.js when installed via npm

### ISSUE THREAD

**Issue by ryandeussing** [Teddy-Zhu/vue-smoothscroll#2]
It works if you move and rename the file from `node_modules/vue-smoothscroll/dist/vue-smoothscroll.js` to `node_modules/vue-smoothscroll/smoothscroll.js`

**Comment by Teddy-Zhu** [comment]
i try use vue-smoothscroll in project , it works.
```javascript
import VueSmoothScroll from 'vue-smoothscroll';

Vue.use(VueSmoothScroll);
```
can you show me some the example for the error

**Comment by ryandeussing** [comment]
To recreate:

- Vue 2.0 with `vue-templates/webpack`
- `npm install vue-scroll`
- `import VueSmoothScroll from 'vue-smoothscroll';` and `Vue.use(VueSmoothScroll);` added to `main.js`

Error:

```
ERROR in ./~/vue-smoothscroll/smoothscroll.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/myname/repos/myrepo/node_modules/vue-smoothscroll/smoothscroll.js'
    at Error (native)
```

Thanks!

**Comment by Teddy-Zhu** [comment]
I try to fix the error , please try again .thx
