### ISSUE TITLE
VueJS is compatible with IE9-10, this plugin is not

### ISSUE THREAD

**Issue by jeerbl** [Teddy-Zhu/vue-smoothscroll#3]
Hello,

During a test I did on IE9 and IE10, my VueJS app did not work because of this plugin, because the compiled JS file uses the `let` keyword which is [not available on IE9-10](http://caniuse.com/#feat=let).

To fix this, the JS file should be compiled with Babel using Babel [`transform-es2015-block-scoping`](http://babeljs.io/docs/plugins/transform-es2015-block-scoping/) plugin.

I will provide a pull request to fix that, by providing a `.babelrc` file.

Thanks and tell me if this is OK on your side.

Jerome

**Comment by Teddy-Zhu** [comment]
thank you for your pr .

**Comment by jeerbl** [comment]
Hello @Teddy-Zhu,

Unfortunately your fix introduced an issue. `options` is no more defined so `Vue.directive(options.name, ...` is throwing an error. You replaced this:

```javascript
install(Vue, options = { name: 'smoothscroll' }) {
```

with this:
```javascript
install: function (Vue) {
```

therefore `options` is no more defined and no more has a default value.

Opening a pull request to fix this.

Thanks,
Jerome
