### ISSUE TITLE
NPM package doesn't have options variable.

### ISSUE THREAD

**Issue by desprit** [Teddy-Zhu/vue-smoothscroll#8]
NPM package is probably out of date. It doesn't have this part:
https://github.com/Teddy-Zhu/vue-smoothscroll/blob/master/dist/vue-smoothscroll.js#L60
Which causes issues. Manually adding `var options = options || { name: 'smoothscroll' };` resolved the problem.

**Comment by Teddy-Zhu** [comment]
try to update npm module version to 0.1.0, thx
